### ISSUE TITLE
Problem with bulgarian input method

### ISSUE THREAD

**Issue by dinkonin** [a13/reverse-im.el#1]
Hello, when I try to activate the `bulgarian-phonetic` input method with `(reverse-im-activate "bulgarian-phonetic")` i get this error 

> Wrong number of arguments: nil, 4

If i try `bulgarian-bds` everything works OK. I'm using the latest MELPA version on emacs 25.2 (windows)
I've checked `list-input-methods` and I see `bulgarian-phonetic` in the list.

**Comment by a13** [comment]
Thanks for feedback, I have successfully reproduced your issue, trying to fix ASAP!

**Comment by a13** [comment]
Quickfixed, but MELPA packaging can take from hour to 6. Until then you can download fixed file directly, or put this snippet in your config (before reverse-im-activate call):
```
(defun reverse-im--key-def (map mod)
  "Return a list of last two arguments for `define-key' for MAP with MOD modifier."
  (pcase map
    (`(,keychar ,def)
     (let ((from (quail-get-translation def (char-to-string keychar) 1)))
       (and (characterp from) (characterp keychar) (not (= from keychar))
            (list
             (vector (append mod (list from)))
             (vector (append mod (list keychar)))))))
    (_ nil)))
```

**Comment by dinkonin** [comment]
Yes its OK now. Cheers and thanks.

**Comment by dinkonin** [comment]
Yes M-/ is working F1-k M-/ produces this

> M-/ runs the command dabbrev-expand (found in global-map), which is an
interactive autoloaded compiled Lisp function in ‘dabbrev.el’. It is bound to M-/.

But "/" is the same in `bulgarian-phonetic` as in english there is no cyrillic letter mapped there. I have binding "C-`" which in bulgarian-phonetic is "C-ч" , and it translating alright

The only thing I can't figure out is how to map for example "y" and "n" question prompts (for example in the Save file prompt") to their cyrillic counterparts.

**Comment by a13** [comment]
> The only thing I can't figure out is how to map for example "y" and "n" question prompts (for example in the Save file prompt") to their cyrillic counterparts.

@dinkonin  JFYI, this part should work well in Emacs 27+
