### ISSUE TITLE
reverse-im--im-to-keymap wrong-number-of-arguments (2 . 4) 5

### ISSUE THREAD

**Issue by abone28** [a13/reverse-im.el#13]
Function reverse-im--im-to-keymap calls alist-get with 5 arguments

(alist-get input-method reverse-im--keymaps-alist nil nil #'string=)

In Emacs 25.2.2 from Ubuntu 18.04.4 alist-get accepts only 4 arguments, so reverse-im--im-to-keymap fails with error wrong-number-of-arguments (2 . 4) 5

**Comment by a13** [comment]
I hope it's closed in 48bdf14f9ea1b5853007dd9e18a8da7f72e9a7fb @abone28 please check

**Comment by a13** [comment]
Closing, feel free to reopen if the fix doesn't work for you
