### ISSUE TITLE
advice for y-or-n-p

### ISSUE THREAD

**Issue by a13** [a13/reverse-im.el#2]

**Comment by jurta** [comment]
I wonder if you closed this issue because it's possible to add mappings to `query-replace-map` like

```elisp
(define-key query-replace-map "ы" 'act)
(define-key query-replace-map "н" 'skip)
(define-key query-replace-map "Ы" 'act)
(define-key query-replace-map "Н" 'skip)
(define-key query-replace-map "е" 'edit-replacement)
(define-key query-replace-map "Е" 'edit-replacement)
(define-key query-replace-map "Я" 'exit)
```

Anyway there is no more such problems in Emacs 27 where `y-or-n-p` now uses normal minibuffer where keys are translated using standard mapping implemented by this package.
