### ISSUE TITLE
Doom doctor detects wrong type argument

### ISSUE THREAD

**Issue by Omrigan** [a13/reverse-im.el#24]
Configuration: 
```
(use-package! reverse-im
  :custom
  (reverse-im-input-methods '("russian-computer"))
  :config
  (reverse-im-mode t)
  (after! evil
    (define-key evil-normal-state-map (kbd "C-х") #'evil-force-normal-state)
    (define-key evil-insert-state-map (kbd "C-х") #'evil-normal-state)
    (define-key evil-visual-state-map (kbd "C-х") #'evil-exit-visual-state)))
```

Log: https://gist.github.com/Omrigan/735c124348ba299bd4f5770356793933

**Comment by a13** [comment]
I'm not familiar with doom doctor, but it looks like the error happens because `quail-use-package` returns `nil` and Doom doctor expects a string. Given the fact that Quail is a built-in Emacs package, I suppose it's a Doom issue.

**Comment by Svadkos** [comment]
It was fixed https://github.com/hlissner/doom-emacs/issues/5253
