### ISSUE TITLE
Quail Completions buffer

### ISSUE THREAD

**Issue by dinkonin** [a13/reverse-im.el#3]
Hello, when I enable reverse-im, on every startup I get an empty `*Quail Completions*` buffer in my buffer list , is it possible to remove it from within the package or should I kill it with custom a function.

**Comment by a13** [comment]
But there only an empty buffer, I have hundreds of them opened any time. :)

Though, since quail is used only for translation once you call reverse-im-activate — we actually don't need them anymore and I hope it can be killed without any pain — 341e1d7 

Thanks!
