### ISSUE TITLE
Meta bindings doesn't work with Russian (windows)

### ISSUE THREAD

**Issue by habamax** [a13/reverse-im.el#4]
You have in description that Meta bindings are translated too. 
I have tried Meta+а, Meta+и -- they do nothing (I expect them to move word forward, backward)

Are Meta bindings supported?

Thx!

PS 
I have tried to add  (add-to-list 'reverse-im-modifiers 'meta) -- doesn't work too.

PPS
Ctrl+Meta+а and Ctrl+Meta+и works...

PPPS
My config is
(use-package reverse-im
  :config
  (add-to-list 'reverse-im-modifiers 'meta)
  (reverse-im-activate "russian-computer"))

**Comment by habamax** [comment]
If I do `ESC а` or `ESC и` then it works -- I can move forward word and backward word.

**Comment by a13** [comment]
Are you using dvorak/colemak or any other non-standard keyboard layout?

**Comment by a13** [comment]
meta key is already in reverse-im-modifiers list, so there's no need to add it.

What does M-x describe-key M-и say? Do you use any non-standard layout (dvorak, colemak etc)?

**Comment by habamax** [comment]
I use standard qwerty

`C-h k M-и` does nothing. Looks like nothing was pressed at all.

**Comment by a13** [comment]
Does it work in english layout? (M-b)?

**Comment by habamax** [comment]
Yes it works in english layout. (M-b)

I am not sure where to check if M-и works in another applications though.

I have binded M-m to as expand-region hotkey and it works for M-ь

**Comment by habamax** [comment]
Found the problem -- it works with Left Alt but doesn't work with the Right Alt which is AltGr.

**Comment by habamax** [comment]
So I have solved it by remapping on OS level AltGr to Left Alt.

Thx!
