### ISSUE TITLE
reverse-im--activate-key-def: Key sequence M-ESC starts with non-prefix key ESC

### ISSUE THREAD

**Issue by tareefdev** [a13/reverse-im.el#5]
I just installed `reverse-im` via:

`M-x package-install RET reverse-im RET`

then I added `(require 'reverse-im)` to my `.emacs`, I use  `arabic` for `reverse-im-add-input-method`, but I when I call `M-x reverse-im-mode RET` I got this message:

`reverse-im--activate-key-def: Key sequence M-ESC starts with non-prefix key ESC`

and `reverse-im` doesn't work as I expected.

I use GNU Emacs 25.3.1 under Fedora 27

**Comment by a13** [comment]
Thanks, I've reproduced it clearly on my machine, will try to fix ASAP!

**Comment by tareefdev** [comment]
Thanks for your work :)

**Comment by a13** [comment]
WIP: Found the cause of the bug: the thing is `C-[` (which keycode is 91) is an ESC key

**Comment by a13** [comment]
and `ESC` is a prefix key, but we can't bind prefix keys only

**Comment by a13** [comment]
Sorry, I don't have much time right now, so you can try to put it somewhere in your configuration file (after reverse-im)
```
(defvar reverse-im--ignored-keys
      ;; See issue #5 https://github.com/a13/reverse-im.el/issues/5
      '([(control meta 91)]
        [(super meta 91)]
        [(super control meta 91)]
        [(meta 93)]
        [(control meta 93)]
        [(super meta 93)]
        [(super control meta 93)]
        [(meta 1613)]
        [(control meta 1613)]
        [(super meta 1613)]
        [(super control meta 1613)]
        [(meta 1616)]
        [(control meta 1616)]
        [(super meta 1616)]
        [(super control meta 1616)]
        [(meta 62)]
        [(control meta 62)]
        [(super meta 62)]
        [(super control meta 62)]
        [(meta 60)]
        [(control meta 60)]
        [(super meta 60)]
        [(super control meta 60)]
        [(meta 1563)]
        [(control meta 1563)]
        [(super meta 1563)]
        [(super control meta 1563)]
        [(meta 215)]
        [(control meta 215)]
        [(super meta 215)]
        [(super control meta 215)]
        [(meta 247)]
        [(control meta 247)]
        [(super meta 247)]
        [(super control meta 247)]
        [(meta 96)]
        [(control meta 96)]
        [(super meta 96)]
        [(super control meta 96)]
        [(meta 1573)]
        [(control meta 1573)]
        [(super meta 1573)]
        [(super control meta 1573)]
        [(meta 1612)]
        [(control meta 1612)]
        [(super meta 1612)]
        [(super control meta 1612)]
        [(meta 1615)]
        [(control meta 1615)]
        [(super meta 1615)]
        [(super control meta 1615)]
        [(meta 1611)]
        [(control meta 1611)]
        [(super meta 1611)]
        [(super control meta 1611)]
        [(meta 1614)]
        [(control meta 1614)]
        [(super meta 1614)]
        [(super control meta 1614)]
        [(meta 1617)]
        [(control meta 1617)]
        [(super meta 1617)]
        [(super control meta 1617)]
        [(meta 1584)]
        [(control meta 1584)]
        [(super meta 1584)]
        [(super control meta 1584)]))

(defun reverse-im--activate-key-def (keymap kd)
  "Add to KEYMAP KD key/definition list."
  (when kd
    (cl-destructuring-bind (key def) kd
      (unless (member key reverse-im--ignored-keys)
        (define-key keymap key def)))))
```

**Comment by a13** [comment]
I don't have an arabic layout in my system, so can't check it myself, but at least `M-x reverse-im-mode` runs without errors.

I'll try to find a better solution little later.

**Comment by tareefdev** [comment]
I put the previous section in `.emacs` file and the problem has been solved.

> I'll try to find a better solution little later.

Thanks for you again :)

**Comment by tareefdev** [comment]
The shortcuts with Meta key didn't work. is it a normal behaviour with  reverse-im?

**Comment by a13** [comment]
It is not, but see snippet above, we turned some of them off for a some (unknown for now) reason, sorry, I don't have much time to solve it right now

**Comment by a13** [comment]
BTW, did you try reverse-im with any other keyboard layout before?

**Comment by tareefdev** [comment]
> BTW, did you try reverse-im with any other keyboard layout before?

It's work fine with Turkish

**Comment by a13** [comment]
hmmm, then maybe it has something with bidirectional stuff …

**Comment by tareefdev** [comment]
Yes I can confirm that the new version solved this issue, thanks a lot to for your time and efforts.

**Comment by a13** [comment]
Thanks for the issue!
