### ISSUE TITLE
"Required feature `cl-seq' was not provided" in emacs 24.5.1

### ISSUE THREAD

**Issue by aragaer** [a13/reverse-im.el#7]
Debugger entered--Lisp error: (error "Required feature `cl-seq' was not provided")
      require(cl-seq)
      eval-buffer(#<buffer  *load*-649669> nil "/home/aragaer/.emacs.d/elpa/reverse-im-20180213.525/reverse-im.el" nil t)  ; Reading at buffer position 1259
      load-with-code-conversion("/home/aragaer/.emacs.d/elpa/reverse-im-20180213.525/reverse-im.el" "/home/aragaer/.emacs.d/elpa/reverse-im-20180213.525/reverse-im.el" nil t)
      require(reverse-im)```

**Comment by aragaer** [comment]
When replaced with `(require 'cl)`:

    Debugger entered--Lisp error: (void-function alist-get)

**Comment by a13** [comment]
I removed cl-seq dependency, bumped minimal supported version, so closing this one
