### ISSUE TITLE
Doesn't work with org-agenda

### ISSUE THREAD

**Issue by a13** [a13/reverse-im.el#9]

**Comment by jurta** [comment]
Indeed, it doesn't work with packages that read a key explicitly by using such low-level functions like `read-key-sequence`.  There are good news that in Emacs 27 more functions like `y-or-n-p` now use normal minibuffer where keys are translated using standard mapping supported by this package.

So these packages like `org` and `magit` should use the same solution that reads a key using keymaps in the minibuffer.

**Comment by a13** [comment]
BTW, it looks like the new magit (which uses transient) works well :)

**Comment by a13** [comment]
a workaround was introduced in 41d9a04, closing for now
